version: '3.8'

services:
    backend:
        build:
            context: ./api1
            dockerfile: dockerfile
        command: 'python api1/main.py'
        ports:
            - 8001:5000
        volumes:
            - .:/app
        env_file: 
            - .env
        depends_on:
            - db

    db:
        image: postgres:latest
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ".db:/var/lib/postgresql/data"
        env_file:
            - .env
