version: '3.8'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 3306:3306
        networks: 
            - backend_net
        volumes:
            - ./db_data:/var/lib/postgresql/data"
        env_file:
            - .env

    backend:
        build:
            context: ./api1
            dockerfile: dockerfile
        command: bash -c "echo 'waiting for db start up' && sleep 20 && python api1/main.py" 
        restart: on-failure
        ports:
            - 8001:5000
        networks: 
            - backend_net
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3306"]
            interval: 30s
            timeout: 20s
            retries: 5
        volumes:
            - .:/app
        links:
            - db:db
        env_file: 
            - .env
        depends_on:
           - db

    scheduler:
        build:
            context: ./scheduler
            dockerfile: dockerfile-sc
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8001"]
            interval: 30s
            timeout: 60s
            retries: 50
        ports:
            - 8002:8005
        volumes:
            - .:/schedule_batch
        networks: 
            - backend_net
        links:
            - db:db
        env_file: 
            - .env
        depends_on: 
            - db
            - backend
volumes: 
    db-data:
    
networks:
    backend_net:
        driver: "bridge"
