FROM python:3.9
ENV PYTHONUNBUFFERED 1
WORKDIR /scheduler
COPY requirements.txt /scheduler/requirements.txt
COPY organization.yml /scheduler/organization.yml
RUN pip install -r requirements.txt
COPY . /scheduler
CMD ["python", "batch_scheduler.py"]